# Medieval Kingdom - Castle builder (generated by tools/generate_castle_function.py)
# Run with:  /function build_castle   (cheats ON, stand on open flat ground)
# Builds a 41x41 castle around you and summons the Fire Dragon over the treasure!

fill ~-20 ~-1 ~-20 ~20 ~-1 ~20 stonebrick
fill ~-20 ~0 ~-20 ~20 ~17 ~20 air
fill ~-20 ~0 ~-20 ~20 ~6 ~-19 stonebrick
fill ~-20 ~0 ~19 ~20 ~6 ~20 stonebrick
fill ~-20 ~0 ~-18 ~-19 ~6 ~18 stonebrick
fill ~19 ~0 ~-18 ~20 ~6 ~18 stonebrick
fill ~-20 ~7 ~-20 ~20 ~7 ~-20 stonebrick
fill ~-20 ~7 ~20 ~20 ~7 ~20 stonebrick
fill ~-20 ~7 ~-20 ~-20 ~7 ~20 stonebrick
fill ~20 ~7 ~-20 ~20 ~7 ~20 stonebrick
setblock ~-20 ~8 ~-20 stonebrick
setblock ~-20 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-20 stonebrick
setblock ~20 ~8 ~-20 stonebrick
setblock ~-18 ~8 ~-20 stonebrick
setblock ~-18 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-18 stonebrick
setblock ~20 ~8 ~-18 stonebrick
setblock ~-16 ~8 ~-20 stonebrick
setblock ~-16 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-16 stonebrick
setblock ~20 ~8 ~-16 stonebrick
setblock ~-14 ~8 ~-20 stonebrick
setblock ~-14 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-14 stonebrick
setblock ~20 ~8 ~-14 stonebrick
setblock ~-12 ~8 ~-20 stonebrick
setblock ~-12 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-12 stonebrick
setblock ~20 ~8 ~-12 stonebrick
setblock ~-10 ~8 ~-20 stonebrick
setblock ~-10 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-10 stonebrick
setblock ~20 ~8 ~-10 stonebrick
setblock ~-8 ~8 ~-20 stonebrick
setblock ~-8 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-8 stonebrick
setblock ~20 ~8 ~-8 stonebrick
setblock ~-6 ~8 ~-20 stonebrick
setblock ~-6 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-6 stonebrick
setblock ~20 ~8 ~-6 stonebrick
setblock ~-4 ~8 ~-20 stonebrick
setblock ~-4 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-4 stonebrick
setblock ~20 ~8 ~-4 stonebrick
setblock ~-2 ~8 ~-20 stonebrick
setblock ~-2 ~8 ~20 stonebrick
setblock ~-20 ~8 ~-2 stonebrick
setblock ~20 ~8 ~-2 stonebrick
setblock ~0 ~8 ~-20 stonebrick
setblock ~0 ~8 ~20 stonebrick
setblock ~-20 ~8 ~0 stonebrick
setblock ~20 ~8 ~0 stonebrick
setblock ~2 ~8 ~-20 stonebrick
setblock ~2 ~8 ~20 stonebrick
setblock ~-20 ~8 ~2 stonebrick
setblock ~20 ~8 ~2 stonebrick
setblock ~4 ~8 ~-20 stonebrick
setblock ~4 ~8 ~20 stonebrick
setblock ~-20 ~8 ~4 stonebrick
setblock ~20 ~8 ~4 stonebrick
setblock ~6 ~8 ~-20 stonebrick
setblock ~6 ~8 ~20 stonebrick
setblock ~-20 ~8 ~6 stonebrick
setblock ~20 ~8 ~6 stonebrick
setblock ~8 ~8 ~-20 stonebrick
setblock ~8 ~8 ~20 stonebrick
setblock ~-20 ~8 ~8 stonebrick
setblock ~20 ~8 ~8 stonebrick
setblock ~10 ~8 ~-20 stonebrick
setblock ~10 ~8 ~20 stonebrick
setblock ~-20 ~8 ~10 stonebrick
setblock ~20 ~8 ~10 stonebrick
setblock ~12 ~8 ~-20 stonebrick
setblock ~12 ~8 ~20 stonebrick
setblock ~-20 ~8 ~12 stonebrick
setblock ~20 ~8 ~12 stonebrick
setblock ~14 ~8 ~-20 stonebrick
setblock ~14 ~8 ~20 stonebrick
setblock ~-20 ~8 ~14 stonebrick
setblock ~20 ~8 ~14 stonebrick
setblock ~16 ~8 ~-20 stonebrick
setblock ~16 ~8 ~20 stonebrick
setblock ~-20 ~8 ~16 stonebrick
setblock ~20 ~8 ~16 stonebrick
setblock ~18 ~8 ~-20 stonebrick
setblock ~18 ~8 ~20 stonebrick
setblock ~-20 ~8 ~18 stonebrick
setblock ~20 ~8 ~18 stonebrick
setblock ~20 ~8 ~-20 stonebrick
setblock ~20 ~8 ~20 stonebrick
setblock ~-20 ~8 ~20 stonebrick
setblock ~20 ~8 ~20 stonebrick
fill ~-20 ~0 ~-20 ~-14 ~12 ~-14 stonebrick
fill ~-19 ~1 ~-19 ~-15 ~11 ~-15 air
fill ~-20 ~12 ~-20 ~-14 ~12 ~-14 stonebrick
setblock ~-20 ~13 ~-20 stonebrick
setblock ~-20 ~13 ~-14 stonebrick
setblock ~-18 ~13 ~-20 stonebrick
setblock ~-18 ~13 ~-14 stonebrick
setblock ~-16 ~13 ~-20 stonebrick
setblock ~-16 ~13 ~-14 stonebrick
setblock ~-14 ~13 ~-20 stonebrick
setblock ~-14 ~13 ~-14 stonebrick
setblock ~-20 ~13 ~-20 stonebrick
setblock ~-14 ~13 ~-20 stonebrick
setblock ~-20 ~13 ~-18 stonebrick
setblock ~-14 ~13 ~-18 stonebrick
setblock ~-20 ~13 ~-16 stonebrick
setblock ~-14 ~13 ~-16 stonebrick
setblock ~-20 ~13 ~-14 stonebrick
setblock ~-14 ~13 ~-14 stonebrick
setblock ~-17 ~3 ~-20 air
setblock ~-17 ~3 ~-14 air
setblock ~-20 ~3 ~-17 air
setblock ~-14 ~3 ~-17 air
setblock ~-17 ~13 ~-17 torch
fill ~-20 ~0 ~14 ~-14 ~12 ~20 stonebrick
fill ~-19 ~1 ~15 ~-15 ~11 ~19 air
fill ~-20 ~12 ~14 ~-14 ~12 ~20 stonebrick
setblock ~-20 ~13 ~14 stonebrick
setblock ~-20 ~13 ~20 stonebrick
setblock ~-18 ~13 ~14 stonebrick
setblock ~-18 ~13 ~20 stonebrick
setblock ~-16 ~13 ~14 stonebrick
setblock ~-16 ~13 ~20 stonebrick
setblock ~-14 ~13 ~14 stonebrick
setblock ~-14 ~13 ~20 stonebrick
setblock ~-20 ~13 ~14 stonebrick
setblock ~-14 ~13 ~14 stonebrick
setblock ~-20 ~13 ~16 stonebrick
setblock ~-14 ~13 ~16 stonebrick
setblock ~-20 ~13 ~18 stonebrick
setblock ~-14 ~13 ~18 stonebrick
setblock ~-20 ~13 ~20 stonebrick
setblock ~-14 ~13 ~20 stonebrick
setblock ~-17 ~3 ~14 air
setblock ~-17 ~3 ~20 air
setblock ~-20 ~3 ~17 air
setblock ~-14 ~3 ~17 air
setblock ~-17 ~13 ~17 torch
fill ~14 ~0 ~-20 ~20 ~12 ~-14 stonebrick
fill ~15 ~1 ~-19 ~19 ~11 ~-15 air
fill ~14 ~12 ~-20 ~20 ~12 ~-14 stonebrick
setblock ~14 ~13 ~-20 stonebrick
setblock ~14 ~13 ~-14 stonebrick
setblock ~16 ~13 ~-20 stonebrick
setblock ~16 ~13 ~-14 stonebrick
setblock ~18 ~13 ~-20 stonebrick
setblock ~18 ~13 ~-14 stonebrick
setblock ~20 ~13 ~-20 stonebrick
setblock ~20 ~13 ~-14 stonebrick
setblock ~14 ~13 ~-20 stonebrick
setblock ~20 ~13 ~-20 stonebrick
setblock ~14 ~13 ~-18 stonebrick
setblock ~20 ~13 ~-18 stonebrick
setblock ~14 ~13 ~-16 stonebrick
setblock ~20 ~13 ~-16 stonebrick
setblock ~14 ~13 ~-14 stonebrick
setblock ~20 ~13 ~-14 stonebrick
setblock ~17 ~3 ~-20 air
setblock ~17 ~3 ~-14 air
setblock ~14 ~3 ~-17 air
setblock ~20 ~3 ~-17 air
setblock ~17 ~13 ~-17 torch
fill ~14 ~0 ~14 ~20 ~12 ~20 stonebrick
fill ~15 ~1 ~15 ~19 ~11 ~19 air
fill ~14 ~12 ~14 ~20 ~12 ~20 stonebrick
setblock ~14 ~13 ~14 stonebrick
setblock ~14 ~13 ~20 stonebrick
setblock ~16 ~13 ~14 stonebrick
setblock ~16 ~13 ~20 stonebrick
setblock ~18 ~13 ~14 stonebrick
setblock ~18 ~13 ~20 stonebrick
setblock ~20 ~13 ~14 stonebrick
setblock ~20 ~13 ~20 stonebrick
setblock ~14 ~13 ~14 stonebrick
setblock ~20 ~13 ~14 stonebrick
setblock ~14 ~13 ~16 stonebrick
setblock ~20 ~13 ~16 stonebrick
setblock ~14 ~13 ~18 stonebrick
setblock ~20 ~13 ~18 stonebrick
setblock ~14 ~13 ~20 stonebrick
setblock ~20 ~13 ~20 stonebrick
setblock ~17 ~3 ~14 air
setblock ~17 ~3 ~20 air
setblock ~14 ~3 ~17 air
setblock ~20 ~3 ~17 air
setblock ~17 ~13 ~17 torch
fill ~-5 ~0 ~-20 ~-3 ~10 ~-18 stonebrick
fill ~-5 ~1 ~-19 ~-4 ~9 ~-19 air
setblock ~-5 ~11 ~-20 stonebrick
setblock ~-5 ~11 ~-19 stonebrick
setblock ~-3 ~11 ~-20 stonebrick
setblock ~-3 ~11 ~-19 stonebrick
fill ~3 ~0 ~-20 ~5 ~10 ~-18 stonebrick
fill ~4 ~1 ~-19 ~5 ~9 ~-19 air
setblock ~3 ~11 ~-20 stonebrick
setblock ~3 ~11 ~-19 stonebrick
setblock ~5 ~11 ~-20 stonebrick
setblock ~5 ~11 ~-19 stonebrick
fill ~-2 ~0 ~-20 ~2 ~4 ~-19 air
fill ~-2 ~4 ~-20 ~2 ~4 ~-19 iron_bars
setblock ~-3 ~4 ~-18 torch
setblock ~3 ~4 ~-18 torch
fill ~-6 ~0 ~12 ~6 ~13 ~19 stonebrick
fill ~-5 ~1 ~13 ~5 ~12 ~18 air
fill ~-1 ~1 ~12 ~1 ~3 ~12 air
fill ~-5 ~6 ~13 ~5 ~6 ~18 stonebrick
setblock ~4 ~7 ~13 air
fill ~-6 ~14 ~12 ~6 ~14 ~19 stonebrick
setblock ~-6 ~15 ~12 stonebrick
setblock ~-6 ~15 ~19 stonebrick
setblock ~-4 ~15 ~12 stonebrick
setblock ~-4 ~15 ~19 stonebrick
setblock ~-2 ~15 ~12 stonebrick
setblock ~-2 ~15 ~19 stonebrick
setblock ~0 ~15 ~12 stonebrick
setblock ~0 ~15 ~19 stonebrick
setblock ~2 ~15 ~12 stonebrick
setblock ~2 ~15 ~19 stonebrick
setblock ~4 ~15 ~12 stonebrick
setblock ~4 ~15 ~19 stonebrick
setblock ~6 ~15 ~12 stonebrick
setblock ~6 ~15 ~19 stonebrick
setblock ~-4 ~4 ~19 air
setblock ~-4 ~9 ~19 air
setblock ~0 ~4 ~19 air
setblock ~0 ~9 ~19 air
setblock ~4 ~4 ~19 air
setblock ~4 ~9 ~19 air
setblock ~-3 ~2 ~14 torch
setblock ~3 ~2 ~14 torch
setblock ~-3 ~8 ~14 torch
setblock ~4 ~7 ~17 chest
replaceitem block ~4 ~7 ~17 slot.container 0 emerald 12
replaceitem block ~4 ~7 ~17 slot.container 1 golden_apple 2
replaceitem block ~4 ~7 ~17 slot.container 2 md:iron_plating 4
replaceitem block ~4 ~7 ~17 slot.container 3 arrow 64
fill ~-2 ~0 ~-2 ~2 ~0 ~2 gold_block
fill ~-1 ~1 ~-1 ~1 ~1 ~1 gold_block
setblock ~0 ~2 ~0 diamond_block
setblock ~-3 ~0 ~-3 emerald_block
setblock ~-3 ~0 ~3 emerald_block
setblock ~3 ~0 ~-3 emerald_block
setblock ~3 ~0 ~3 emerald_block
setblock ~4 ~0 ~0 chest
replaceitem block ~4 ~0 ~0 slot.container 0 diamond 5
replaceitem block ~4 ~0 ~0 slot.container 1 emerald 10
replaceitem block ~4 ~0 ~0 slot.container 2 gold_ingot 20
replaceitem block ~4 ~0 ~0 slot.container 3 golden_apple 3
replaceitem block ~4 ~0 ~0 slot.container 4 experience_bottle 16
replaceitem block ~4 ~0 ~0 slot.container 5 md:dragon_scale 4
setblock ~-4 ~0 ~0 chest
replaceitem block ~-4 ~0 ~0 slot.container 0 diamond 5
replaceitem block ~-4 ~0 ~0 slot.container 1 emerald 10
replaceitem block ~-4 ~0 ~0 slot.container 2 gold_ingot 20
replaceitem block ~-4 ~0 ~0 slot.container 3 golden_apple 3
replaceitem block ~-4 ~0 ~0 slot.container 4 experience_bottle 16
replaceitem block ~-4 ~0 ~0 slot.container 5 md:dragon_scale 4
setblock ~0 ~0 ~4 chest
replaceitem block ~0 ~0 ~4 slot.container 0 diamond 5
replaceitem block ~0 ~0 ~4 slot.container 1 emerald 10
replaceitem block ~0 ~0 ~4 slot.container 2 gold_ingot 20
replaceitem block ~0 ~0 ~4 slot.container 3 golden_apple 3
replaceitem block ~0 ~0 ~4 slot.container 4 experience_bottle 16
replaceitem block ~0 ~0 ~4 slot.container 5 md:dragon_scale 4
replaceitem block ~0 ~0 ~4 slot.container 6 totem_of_undying 1
setblock ~-16 ~7 ~-19 torch
setblock ~-16 ~7 ~19 torch
setblock ~-19 ~7 ~-16 torch
setblock ~19 ~7 ~-16 torch
setblock ~-12 ~7 ~-19 torch
setblock ~-12 ~7 ~19 torch
setblock ~-19 ~7 ~-12 torch
setblock ~19 ~7 ~-12 torch
setblock ~-8 ~7 ~-19 torch
setblock ~-8 ~7 ~19 torch
setblock ~-19 ~7 ~-8 torch
setblock ~19 ~7 ~-8 torch
setblock ~-4 ~7 ~-19 torch
setblock ~-4 ~7 ~19 torch
setblock ~-19 ~7 ~-4 torch
setblock ~19 ~7 ~-4 torch
setblock ~0 ~7 ~-19 torch
setblock ~0 ~7 ~19 torch
setblock ~-19 ~7 ~0 torch
setblock ~19 ~7 ~0 torch
setblock ~4 ~7 ~-19 torch
setblock ~4 ~7 ~19 torch
setblock ~-19 ~7 ~4 torch
setblock ~19 ~7 ~4 torch
setblock ~8 ~7 ~-19 torch
setblock ~8 ~7 ~19 torch
setblock ~-19 ~7 ~8 torch
setblock ~19 ~7 ~8 torch
setblock ~12 ~7 ~-19 torch
setblock ~12 ~7 ~19 torch
setblock ~-19 ~7 ~12 torch
setblock ~19 ~7 ~12 torch
setblock ~16 ~7 ~-19 torch
setblock ~16 ~7 ~19 torch
setblock ~-19 ~7 ~16 torch
setblock ~19 ~7 ~16 torch
summon md:archer ~-17 ~13 ~-17
summon md:archer ~-17 ~13 ~17
summon md:archer ~17 ~13 ~-17
summon md:archer ~17 ~13 ~17
summon md:archer ~0 ~7 ~19
summon md:archer ~19 ~7 ~0
summon md:archer ~-19 ~7 ~0
summon md:archer ~0 ~7 ~-19
summon md:knight ~-2 ~0 ~-15
summon md:knight ~2 ~0 ~-15
summon md:knight ~-7 ~0 ~7
summon md:knight ~7 ~0 ~7
summon md:fire_dragon ~0 ~8 ~0

tellraw @s {"rawtext":[{"text":"§6The castle rises! §cThe Fire Dragon guards its hoard at the heart of the courtyard..."}]}
