#!/usr/bin/env python3
"""
Generates functions/build_castle.mcfunction — a full castle centered on the
player: curtain walls with crenellated parapets, four corner towers, a
gatehouse with portcullis, a rear keep, torch-lit walls, archer guards on the
battlements, knight guards at the gate, and a central treasure mound of gold
where the Fire Dragon is summoned.

Run this script to regenerate the function after tweaking the layout.
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "..",
                   "behavior_packs", "medieval_bp", "functions", "build_castle.mcfunction")

L = []  # command lines
def c(s): L.append(s)
def fill(x0, y0, z0, x1, y1, z1, block):
    c(f"fill ~{x0} ~{y0} ~{z0} ~{x1} ~{y1} ~{z1} {block}")
def setb(x, y, z, block):
    c(f"setblock ~{x} ~{y} ~{z} {block}")

R = 20        # half-width of castle footprint
WALL_H = 6    # curtain wall top (floor of walkway)
TOWER = 12    # corner tower top

c("# Medieval Kingdom - Castle builder (generated by tools/generate_castle_function.py)")
c("# Run with:  /function build_castle   (cheats ON, stand on open flat ground)")
c("# Builds a 41x41 castle around you and summons the Fire Dragon over the treasure!")
c("")

# --- site prep: foundation + clear the volume ---
fill(-R, -1, -R, R, -1, R, "stonebrick")
fill(-R, 0, -R, R, 17, R, "air")

# --- curtain walls (2 thick, y0..WALL_H) ---
fill(-R, 0, -R, R, WALL_H, -R + 1, "stonebrick")        # north (-z)
fill(-R, 0, R - 1, R, WALL_H, R, "stonebrick")          # south (+z)
fill(-R, 0, -R + 2, -R + 1, WALL_H, R - 2, "stonebrick")  # west
fill(R - 1, 0, -R + 2, R, WALL_H, R - 2, "stonebrick")    # east

# --- parapet ring on the outer edge (y7) + merlons (y8, every 2) ---
fill(-R, WALL_H + 1, -R, R, WALL_H + 1, -R, "stonebrick")
fill(-R, WALL_H + 1, R, R, WALL_H + 1, R, "stonebrick")
fill(-R, WALL_H + 1, -R, -R, WALL_H + 1, R, "stonebrick")
fill(R, WALL_H + 1, -R, R, WALL_H + 1, R, "stonebrick")
for i in range(-R, R + 1, 2):
    setb(i, WALL_H + 2, -R, "stonebrick")
    setb(i, WALL_H + 2, R, "stonebrick")
    setb(-R, WALL_H + 2, i, "stonebrick")
    setb(R, WALL_H + 2, i, "stonebrick")

# --- four corner towers (7x7, y0..TOWER, hollow, crenellated) ---
for sx in (-1, 1):
    for sz in (-1, 1):
        x0, x1 = sorted((sx * (R - 6), sx * R))
        z0, z1 = sorted((sz * (R - 6), sz * R))
        fill(x0, 0, z0, x1, TOWER, z1, "stonebrick")
        fill(x0 + 1, 1, z0 + 1, x1 - 1, TOWER - 1, z1 - 1, "air")
        # top floor + crenels
        fill(x0, TOWER, z0, x1, TOWER, z1, "stonebrick")
        for i in range(x0, x1 + 1, 2):
            setb(i, TOWER + 1, z0, "stonebrick")
            setb(i, TOWER + 1, z1, "stonebrick")
        for i in range(z0, z1 + 1, 2):
            setb(x0, TOWER + 1, i, "stonebrick")
            setb(x1, TOWER + 1, i, "stonebrick")
        # arrow slits
        setb((x0 + x1) // 2, 3, z0, "air")
        setb((x0 + x1) // 2, 3, z1, "air")
        setb(x0, 3, (z0 + z1) // 2, "air")
        setb(x1, 3, (z0 + z1) // 2, "air")
        # torch on top
        setb((x0 + x1) // 2, TOWER + 1, (z0 + z1) // 2, "torch")

# --- gatehouse on the north face (-z): flanking pillars + open gate ---
for sx in (-1, 1):
    x0, x1 = sorted((sx * 3, sx * 5))
    fill(x0, 0, -R, x1, 10, -R + 2, "stonebrick")
    fill(x0 + (0 if sx < 0 else 1), 1, -R + 1, x1 - (1 if sx < 0 else 0), 9, -R + 1, "air")
    for i in range(x0, x1 + 1, 2):
        setb(i, 11, -R, "stonebrick")
        setb(i, 11, -R + 1, "stonebrick")
# gate opening + portcullis bars across the top
fill(-2, 0, -R, 2, 4, -R + 1, "air")
fill(-2, 4, -R, 2, 4, -R + 1, "iron_bars")
# lit entrance
setb(-3, 4, -R + 2, "torch")
setb(3, 4, -R + 2, "torch")

# --- rear keep (13 wide, y0..13, hollow, crenellated) ---
fill(-6, 0, 12, 6, 13, R - 1, "stonebrick")
fill(-5, 1, 13, 5, 12, R - 2, "air")
fill(-1, 1, 12, 1, 3, 12, "air")                      # doorway to courtyard
fill(-5, 6, 13, 5, 6, R - 2, "stonebrick")            # second floor
setb(4, 7, 13, "air")                                  # floor hatch
fill(-6, 14, 12, 6, 14, R - 1, "stonebrick")          # roof
for i in range(-6, 7, 2):
    setb(i, 15, 12, "stonebrick")
    setb(i, 15, R - 1, "stonebrick")
# keep windows + light
for x in (-4, 0, 4):
    setb(x, 4, R - 1, "air")
    setb(x, 9, R - 1, "air")
setb(-3, 2, 14, "torch")
setb(3, 2, 14, "torch")
setb(-3, 8, 14, "torch")
# keep treasury chest
setb(4, 7, 17, "chest")
c("replaceitem block ~4 ~7 ~17 slot.container 0 emerald 12")
c("replaceitem block ~4 ~7 ~17 slot.container 1 golden_apple 2")
c("replaceitem block ~4 ~7 ~17 slot.container 2 md:iron_plating 4")
c("replaceitem block ~4 ~7 ~17 slot.container 3 arrow 64")

# --- central treasure mound: the dragon's hoard ---
fill(-2, 0, -2, 2, 0, 2, "gold_block")
fill(-1, 1, -1, 1, 1, 1, "gold_block")
setb(0, 2, 0, "diamond_block")
for sx in (-3, 3):
    for sz in (-3, 3):
        setb(sx, 0, sz, "emerald_block")
# hoard chests on each side of the mound
for (cx, cz) in ((4, 0), (-4, 0), (0, 4)):
    setb(cx, 0, cz, "chest")
    c(f"replaceitem block ~{cx} ~0 ~{cz} slot.container 0 diamond 5")
    c(f"replaceitem block ~{cx} ~0 ~{cz} slot.container 1 emerald 10")
    c(f"replaceitem block ~{cx} ~0 ~{cz} slot.container 2 gold_ingot 20")
    c(f"replaceitem block ~{cx} ~0 ~{cz} slot.container 3 golden_apple 3")
    c(f"replaceitem block ~{cx} ~0 ~{cz} slot.container 4 experience_bottle 16")
    c(f"replaceitem block ~{cx} ~0 ~{cz} slot.container 5 md:dragon_scale 4")
c("replaceitem block ~0 ~0 ~4 slot.container 6 totem_of_undying 1")

# --- torches along the wall walkway (inner ring, every 4) ---
for i in range(-16, 17, 4):
    setb(i, WALL_H + 1, -R + 1, "torch")
    setb(i, WALL_H + 1, R - 1, "torch")
    setb(-R + 1, WALL_H + 1, i, "torch")
    setb(R - 1, WALL_H + 1, i, "torch")

# --- the garrison ---
# archers on every corner tower top
for sx in (-1, 1):
    for sz in (-1, 1):
        c(f"summon md:archer ~{sx * (R - 3)} ~{TOWER + 1} ~{sz * (R - 3)}")
# archers at the middle of each wall walkway
c(f"summon md:archer ~0 ~{WALL_H + 1} ~{R - 1}")
c(f"summon md:archer ~{R - 1} ~{WALL_H + 1} ~0")
c(f"summon md:archer ~{-(R - 1)} ~{WALL_H + 1} ~0")
c(f"summon md:archer ~0 ~{WALL_H + 1} ~{-(R - 1)}")
# knights at the gate and in the courtyard
c("summon md:knight ~-2 ~0 ~-15")
c("summon md:knight ~2 ~0 ~-15")
c("summon md:knight ~-7 ~0 ~7")
c("summon md:knight ~7 ~0 ~7")

# --- the dragon, roused atop its hoard ---
c("summon md:fire_dragon ~0 ~8 ~0")
c("")
c('tellraw @s {"rawtext":[{"text":"§6The castle rises! §cThe Fire Dragon guards its hoard at the heart of the courtyard..."}]}')

with open(OUT, "w") as f:
    f.write("\n".join(L) + "\n")
print(f"wrote {os.path.relpath(OUT)} with {len([l for l in L if l and not l.startswith('#')])} commands")
